LogisticRegression(C = 1.0, solver = 'liblinear' or 'lbfgs' 'sag' or 'saga', max_iter = 100, multi_class = 'ovr', random_state = None, solver = 'liblinear', tol = 0.001)

multi_class = 'ovr' or 'multinomial' for multi-class logistic regression -> mearning one versus rest, we can apply this on the iris dataset cause it has more than two classes

In [12]:
from sklearn import model_selection
from sklearn.linear_model import LogisticRegression
from sklearn import datasets

In [13]:
cancer_data = datasets.load_breast_cancer()
cancer_data

{'data': array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
         1.189e-01],
        [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
         8.902e-02],
        [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
         8.758e-02],
        ...,
        [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
         7.820e-02],
        [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
         1.240e-01],
        [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
         7.039e-02]]),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
        1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
        1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
        1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0

In [14]:
X = cancer_data.data
Y = cancer_data.target

In [15]:
X_train, X_test, Y_train, Y_test = model_selection.train_test_split(X, Y, test_size = 0.3)

In [19]:
model = LogisticRegression(C = 2, solver = 'liblinear')
model

LogisticRegression(C=2, solver='liblinear')

In [21]:
model.fit(X_train, Y_train)

LogisticRegression(C=2, solver='liblinear')

In [22]:
print("Training Score: ", model.score(X_train, Y_train)) # -> Giving us a 95% accuracy

Training Score:  0.957286432160804


In [23]:
print("Testing Score: ", model.score(X_test, Y_test)) # -> Giving us a 96% accuracy

Testing Score:  0.9590643274853801


LogisticRegression(C=2, solver='liblinear') allows you to specify the following parameters:

C: Inverse of regularization strength. Smaller values of C specify stronger regularization. Default value is 1.0.
solver: Algorithm to use in the optimization problem. The 'liblinear' solver is recommended for small datasets, while 'lbfgs', 'sag', and 'saga' are faster for larger ones. The default solver is 'lbfgs'.


The parameter C is the inverse of the regularization strength. A smaller C creates a stronger regularization, which may prevent overfitting but could also lead to underfitting. On the other hand, a larger C results in weaker regularization, allowing the model to fit the data more closely, but potentially overfitting the data. In this case, C=2 might be better than C=1 because it provides slightly weaker regularization, allowing the model to better capture the underlying patterns in the sample cancer dataset

The choice between LogisticRegression(C=2, solver='liblinear') and LogisticRegression(C=1, solver='lbfgs') depends on the dataset and the problem you are trying to solve. In the case of the sample cancer dataset in sklearn, it seems that LogisticRegression(C=2, solver='liblinear') performs better. 

Solver: The choice of solver can also impact the performance of the logistic regression model. In this case, you are comparing liblinear and lbfgs. liblinear is a good choice for small datasets, whereas lbfgs is more suitable for larger datasets scikit-learn.org. The sample cancer dataset in sklearn is relatively small, which might make liblinear a better choice. Additionally, liblinear can handle both L1 and L2 regularization, whereas lbfgs only supports L2 regularization

In [32]:
model.predict_proba(X)

array([[1.00000000e+00, 3.80296513e-15],
       [9.99999644e-01, 3.56235491e-07],
       [9.99999815e-01, 1.85432487e-07],
       ...,
       [9.97470707e-01, 2.52929287e-03],
       [1.00000000e+00, 4.55701722e-11],
       [4.68926811e-02, 9.53107319e-01]])

In [29]:
probabilities = model.predict_proba(X) # -> Gives us the actual probabilities of all data points

In [33]:
probabilities[13] # -> Checking the probability of 13th data point

array([0.25757352, 0.74242648])

In [35]:
# Predictions
model.fit(X_train, Y_train)

LogisticRegression(C=2, solver='liblinear')

In [36]:
model.predict(X_test)

array([1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0,
       0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1,
       0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1,
       0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1])

In [ ]:
# Save the predicted target values to a CSV file using NumPy
np.savetxt("predictions_numpy.csv", predictions, delimiter=",")

In [ ]:
# Create a DataFrame of the predicted target values
predictions_df = pd.DataFrame(predictions, columns=["Predicted Target"])

# Save the DataFrame to a CSV file using Pandas
predictions_df.to_csv("predictions_pandas.csv", index=False)